// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const DEFAULT_SUPABASE_URL = "https://jrsydiofzceoeddjogov.supabase.co";
const DEFAULT_SUPABASE_KEY = "sb_publishable_uE7DPlUSNxgQ1pfEA6nfQA_Z0VDAP4p";

const rawUrl = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_URL = (rawUrl && !rawUrl.includes("bwvocmhcledbwqlpcswp"))
  ? rawUrl
  : DEFAULT_SUPABASE_URL;

// Key selection: If connecting to jrsydiofzceoeddjogov, ensure we do not send the legacy project JWT
const rawPublishable = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const rawAnon = import.meta.env.VITE_SUPABASE_ANON_KEY;
const isLegacyKey = (k?: string) => Boolean(k && k.includes("bwvocmhcledbwqlpcswp"));

const SUPABASE_PUBLISHABLE_KEY = 
  (!isLegacyKey(rawPublishable) && rawPublishable)
    ? rawPublishable
    : (!isLegacyKey(rawAnon) && rawAnon)
      ? rawAnon
      : DEFAULT_SUPABASE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Resilient Edge Function gateway: Routes communication and platform functions directly to local gateway
const LOCAL_GATEWAY_FUNCTIONS = new Set([
  "send-sms-notification",
  "case-send-sms",
  "reprocess-sms-dlq",
  "phone-otp-custom",
  "verify-phone",
  "twilio-test-send",
  "voice-access-token",
  "initiate-voip-call",
  "voice-call-request",
  "voice-twiml-config",
  "voice-twiml-dial",
  "end-voip-call",
  "get-recording-url",
  "create-call-in",
  "renew-call-in",
  "send-in-app-message",
  "send-inbox-reply",
  "send-email-reply",
  "inbox-attachment-ocr",
  "hologram-admin",
  "verify-credentials",
  "resend-events",
]);

async function callLocalGateway(functionName: string, options?: any) {
  let authHeader = options?.headers?.Authorization || options?.headers?.authorization;
  if (!authHeader) {
    try {
      const session = (await supabase.auth.getSession()).data.session;
      if (session?.access_token) {
        authHeader = `Bearer ${session.access_token}`;
      }
    } catch {
      // Session fetch error ignored
    }
  }

  const res = await fetch(`/api/functions/${functionName}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(authHeader ? { Authorization: authHeader } : {}),
      ...(options?.headers || {}),
    },
    body: options?.body ? (typeof options.body === "string" ? options.body : JSON.stringify(options.body)) : undefined,
  });

  const json = await res.json().catch(() => ({}));
  if (res.ok) {
    return { data: json, error: null };
  } else {
    const errorMsg = json?.error || json?.message || `Edge function '${functionName}' failed (HTTP ${res.status})`;
    return { data: null, error: new Error(errorMsg) };
  }
}

const originalInvoke = supabase.functions.invoke.bind(supabase.functions);
supabase.functions.invoke = (async (functionName: string, options?: any) => {
  if (LOCAL_GATEWAY_FUNCTIONS.has(functionName)) {
    return await callLocalGateway(functionName, options);
  }

  try {
    const res = await originalInvoke(functionName, options);
    if (!res.error) return res;

    const is404 =
      res.error?.message?.includes("404") ||
      res.error?.message?.toLowerCase().includes("not found") ||
      (res.error as any)?.context?.status === 404;

    if (!is404) return res;
  } catch {
    // Continue to fallback
  }

  return await callLocalGateway(functionName, options);
}) as typeof supabase.functions.invoke;